### ISSUE TITLE
create plugin lifecycle event that allows injecting headers for batch requests

### ISSUE THREAD

**Issue by mxmul** [Yelp/pyramid-hypernova#17]
We have a use-case where it would be nice to be able to pass some HTTP headers down from the inbound request to the batch endpoint. Let's add a new plugin lifecycle method that can be used to modify the request headers that are sent to the batch endpoint.

The hook should accept the inbound pyramid request and the job group as arguments, and should return a dictionary of headers to be sent with the batch request.

**Comment by chriskuehl** [comment]
I'll pick this up. Potential use-cases to consider:

* Propagating request headers
* Adding distributed tracing headers (e.g. zipkin)
